# -*- coding: utf-8 -*-
"""Patchcore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyJ_dodAfEKJ9ti7HHel-Zcfl3Q5zbHM

Run PatchCore on texture datasets for unsupervised defect detection
"""

# Install anomalib and other dependencies
!pip install anomalib
!pip install pytorch-lightning==2.3.0

import torch
import numpy as np
import matplotlib.pyplot as plt
from anomalib.data import MVTecAD
from anomalib.models import Patchcore
from anomalib.engine import Engine
# from anomalib.utils.visualization import get_visualization_image # Commented out due to ImportError

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

from anomalib.data import MVTecAD
from torchvision import transforms
import anomalib
print(anomalib.__version__)
from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive/sampledatapatch"))

datamodule = MVTecAD(
    root="/content/drive/MyDrive/sampledatapatch",
    category="carpet"
)
datamodule.setup()


# Initialize the PatchCore model with a pre-trained WideResNet50 backbone.
model = Patchcore(
    backbone="wide_resnet50_2",
    layers=["layer2", "layer3"],
    coreset_sampling_ratio=0.1,
)
#
engine = Engine(
   # pixel_metrics=["pro", "aupro"],
   # image_metrics=["auroc", "f1_max"],
    accelerator="auto",
    devices=1,
)

# Fit the model (build the memory bank from normal images).
print("Building PatchCore memory bank...")
engine.fit(model=model, datamodule=datamodule)

# Test the model on the test set.
print("\nTesting model and evaluating metrics...")
test_results = engine.test(model=model, datamodule=datamodule)

print("\n--- Performance Evaluation Metrics ---")

test_results_dict = test_results[0]
for metric_name, value in test_results_dict.items():
    if "auroc" in metric_name or "pro" in metric_name or "f1" in metric_name:
        print(f"{metric_name}: {value:.4f}")

print(type(test_results))
print(test_results)

"""for metric_name, value in test_results.items():
    if "auroc" in metric_name or "pro" in metric_name or "f1" in metric_name:
        print(f"{metric_name}: {value:.4f}")"""

# Create a test dataloader to get some sample images
test_dataloader = datamodule.test_dataloader()
sample_batch = next(iter(test_dataloader))

# Move tensors to device safely depending on batch type
if isinstance(sample_batch, dict):
    sample_batch = {
        k: (v.to(device) if hasattr(v, "to") else v)
        for k, v in sample_batch.items()
    }
elif isinstance(sample_batch, (list, tuple)):
    sample_batch = [
        x.to(device) if hasattr(x, "to") else x
        for x in sample_batch
    ]
else:
    # Single tensor batch
    if hasattr(sample_batch, "to"):
        sample_batch = sample_batch.to(device)

print("\nRunning prediction using Engine...")
prediction_results = engine.predict(model=model, datamodule=datamodule)

print("Type of prediction_results:", type(prediction_results))

#first batch output
predictions = prediction_results[0]

print("Prediction keys:", predictions.keys())

anomalous_indices = (predictions.pred_label == 1).nonzero(as_tuple=True)[0]
normal_indices = (predictions.pred_label == 0).nonzero(as_tuple=True)[0]


# Visualization function
def display_results(predictions, image_index, title):
    image = predictions.image[image_index]
    anomaly_map = predictions.anomaly_map[image_index]

    gt_mask = predictions.gt_mask if hasattr(predictions, "gt_mask") else None

    fig, ax = plt.subplots(1, 3, figsize=(18, 6))

    # Original image
    ax[0].imshow(image.permute(1, 2, 0).cpu().numpy())
    ax[0].set_title("Original Image")
    ax[0].axis("off")

    # Ground truth mask
    if gt_mask is not None:
        mask = gt_mask[image_index]
        ax[1].imshow(mask.squeeze().cpu().numpy(), cmap="gray")
        ax[1].set_title("Ground Truth Mask")
    else:
        ax[1].text(0.5, 0.5, "No GT Mask", ha="center", va="center")
        ax[1].set_title("Ground Truth Mask")
    ax[1].axis("off")

    # Anomaly heatmap
    ax[2].imshow(anomaly_map.squeeze().cpu().numpy(), cmap="hot")
    ax[2].set_title("Anomaly Heatmap")
    ax[2].axis("off")

    fig.suptitle(title, fontsize=16)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()


# Show anomalous sample
if anomalous_indices.numel() > 0:
    display_results(predictions, anomalous_indices[0], "Anomalous Sample Visualization")
else:
    print("No anomalous samples found.")

# Show normal sample
if normal_indices.numel() > 0:
    display_results(predictions, normal_indices[0], "Normal Sample Visualization")
else:
    print("No normal samples found.")