# -*- coding: utf-8 -*-
"""LLM_Assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WE_FQbZJd4ilMQh180UHBRI70i2_I16a

Hands On:-

1. Pretraining  

a. Using distilgpt for textgeneration

b. Chat generation using mistralai/Mistral-7B-Instruct-v0.2

c. Summarize text using T5-small

a. Using distilgpt for textgeneration
"""

from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1

generator = pipeline("text-generation",model="distilgpt2",device=device)

prompt = "Once upon a time in a city of electric lights,"
out = generator(
    prompt,
    max_new_tokens=80,
    do_sample=True,
    top_k=50,
    top_p=0.95,
    temperature=0.8,
    num_return_sequences=2,
    return_full_text=True
)

for i, g in enumerate(out):
    print(f"Sample {i+1}\n{g['generated_text']}\n")

"""
b. Chat generation using mistralai/Mistral-7B-Instruct-v0.2

"""

from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1

chat = pipeline(
    "text-generation",model="mistralai/Mistral-7B-Instruct-v0.2",device=device,)

prompt = "You are an assistant. Convert this paragraph into a friendly, concise reply:\n\nCustomer: My order hasn't arrived and tracking shows delayed. What should I do?"
out = chat(prompt, max_new_tokens=200, do_sample=False)
print(out[0]['generated_text'])

"""c. Summarize text using T5-small"""

from transformers import pipeline
import torch

device = 0 if torch.cuda.is_available() else -1
summarizer = pipeline("summarization", model="t5-small", device=device)

text = """
Deep learning is a subset of machine learning based on artificial neural networks with representation learning.
Learning can be supervised, semi-supervised or unsupervised. Deep-learning architectures such as deep neural networks,
deep belief networks, recurrent neural networks and convolutional neural networks have been applied to fields including
computer vision, speech recognition, natural language processing, audio recognition, social network filtering, machine
translation, bioinformatics and drug design, where they have produced results comparable to and in some cases superior to
human experts.
"""

# T5 prefers shorter inputs; for long documents chunk or use long-models.
summary = summarizer(text, max_length=60, min_length=20, do_sample=False)
print("Summary:", summary[0]['summary_text'])

"""Assignments

1. For Question Answering Use RoBERTa variants, GPT-3/4 fine-tuned on SQuAD
dataset
"""

# a. Using RoBERTa fine-tuned on SQuAD

from transformers import pipeline

qa_model = pipeline("question-answering", model="deepset/roberta-base-squad2")

context = """
The Smart India Hackathon (SIH) is a nationwide initiative to provide students
with a platform to solve some of the pressing problems of society using
innovation, technology, and creativity.
"""

question = "What is the purpose of the Smart India Hackathon?"

result = qa_model(question=question, context=context)

print("Answer:", result['answer'])
print("Confidence:", round(result['score'], 3))

"""2.Compare extractive and abstractive summarization"""

!pip install bert-extractive-summarizer spacy

#Extractive summarization
import nltk
nltk.download('punkt')

from summarizer import Summarizer

text =""" The oldest classical British and Latin writings had little or no space between words and could be written in boustrophedon (alternating directions). Over time, text direction (left to right) became standardized. Word dividers and terminal punctuation became common. The first way to divide sentences into groups was the original paragraphos, similar to an underscore at the beginning of the new group.[1] The Greek parágraphos evolved into the pilcrow (¶), which in English manuscripts in the Middle Ages can be seen inserted inline between sentences.


Indented paragraphs demonstrated in the US Constitution
Ancient manuscripts also divided sentences into paragraphs with line breaks (newline) followed by an initial at the beginning of the next paragraph. An initial is an oversized capital letter, sometimes outdented beyond the margin of the text. This style can be seen, for example, in the original Old English manuscript of Beowulf. Outdenting is still used in English typography, though not commonly.[2] Modern English typography usually indicates a new paragraph by indenting the first line. This style can be seen in the (handwritten) United States Constitution from 1787. For additional ornamentation, a hedera leaf or other symbol can be added to the inter-paragraph white space, or put in the indentation space."""

# Using pre-trained BERT model for extractive summarization
bert_model = Summarizer()
summary = bert_model(text, min_length=60)

print("Extractive Summary:\n", summary)

#Abstractive Summarization

from transformers import pipeline

# Using pretrained BART model for abstractive summarization
abstractive_summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

abstractive_summary = abstractive_summarizer(
    text, max_length=100, min_length=30, do_sample=False
)

print("Abstractive Summary:\n", abstractive_summary[0]['summary_text'])

"""3. Compare retrieval-based vs generative chatbot responses."""

#Retrieval-based
from transformers import pipeline

# Retrieval-based (uses existing knowledge to pick best response)
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

sequence = "The ordered product is damaged and not packed properly."
labels = ["delivery issue", "damaged product", "pricing", "customer service"]

result = classifier(sequence, candidate_labels=labels)
print("Predicted Category:", result['labels'][0])

#Generative based

from transformers import pipeline

# Generative chatbot (creates its own responses)
generator = pipeline("text-generation", model="gpt2")

prompt = "User: What are the benefits of using solar energy?\nChatbot:"
response = generator(prompt, max_length=80, do_sample=True, temperature=0.7)

print("Generative Chatbot Response:", response[0]['generated_text'])

"""4.Apply various prompting techniques and view the difference"""

#Zero shot with API
from huggingface_hub import InferenceClient

client = InferenceClient(token="MY_API")

sequence = "The ordered product is damaged and not packed properly."

labels =["delivery issue", "damaged product", "pricing", "customer service"]

labels_str = ", ".join(labels)

messages = [
    {"role": "system", "content": "You are a Owner of a food delivery company."},
    {"role": "user",   "content": f"Classify the following complaint into one of these categories: {labels_str}\nComplaint: {sequence}\nOnly give the category."}
]
result = client.chat_completion(model="openai/gpt-oss-20b",messages=messages, max_tokens=1500)

print("Generator Output: ",result.choices[0].message.content)

#Few Shot (Hugging Face API)

from huggingface_hub import InferenceClient
client = InferenceClient(token="MY_API")


prompt = """ Classify the news headline into one of the categories: Politics, Business, Sports, Entertainment, Technology.

Example 1:
"Government announces new tax policy for startups."
Category: Business

Example 2:
"India wins the cricket world cup after a thrilling final."
Category: Sports

Example 3:
"New AI model breaks record in language understanding."
Category: Technology

Now classify this:
"Actor wins national award for best performance in drama film."
Category:
 """

messages = [
    {"role": "system", "content": "You are a News classification Analyst."},
    {"role": "user",   "content": prompt} ]
result = client.chat_completion(model="openai/gpt-oss-20b",messages=messages, max_tokens=1500)

print("Generator Output: ",result.choices[0].message.content)

#chain of thought
from huggingface_hub import InferenceClient

client =InferenceClient(token ="MY_API")

prompt="""
Classify this review into Positive, Neutral, or Negative. Explain step-by-step which words and reasoning lead to the label, then give the final category.

Review: "Delivery was late, and the food was cold."

"""
messages = [
    {"role": "system", "content": "You are a Owner of afood delivery company."},
    {"role": "user",   "content": prompt}
]
result = client.chat_completion(model="openai/gpt-oss-20b",messages=messages, max_tokens=1500)

print("Generator Output: ",result.choices[0].message.content)